# Generated by Django 6.0.1 on 2026-01-20 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.AddField(
            model_name='feestructure',
            name='category',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('meals', 'Meals'), ('transport', 'Transport'), ('uniform', 'Uniform'), ('books', 'Books'), ('other', 'Other')], default='tuition', max_length=20),
        ),
        migrations.AddField(
            model_name='feestructure',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('draft', 'Draft')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='fee_type',
            field=models.CharField(choices=[('tuition', 'Tuition'), ('meals', 'Meals'), ('transport', 'Transport'), ('uniform', 'Uniform'), ('books', 'Books'), ('other', 'Other')], default='tuition', max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_account',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_network',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('pending', 'Pending'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='completed', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank Transfer'), ('mobile', 'Mobile Money'), ('card', 'Card'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=20),
        ),
    ]
