# Generated by Django 6.0.1 on 2026-01-18 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('core', '0001_initial'),
        ('schools', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decision', models.CharField(choices=[('promoted', 'Promoted'), ('retained', 'Retained'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('is_automatic', models.BooleanField(default=False, help_text='True if decision was made by system, False if manual')),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('subjects_passed', models.IntegerField(default=0)),
                ('subjects_failed', models.IntegerField(default=0)),
                ('reason', models.TextField(blank=True, help_text='Reason for decision, especially for manual overrides')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('requires_review', models.BooleanField(default=False, help_text='True if missing exams require manual review')),
                ('review_notes', models.TextField(blank=True)),
                ('is_final', models.BooleanField(default=False, help_text='True if promotion is final and cannot be changed')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='schools.academicyear')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_decided', to='staff.staffprofile')),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_from', to='academic.class')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='students.student')),
                ('to_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_to', to='academic.class')),
            ],
            options={
                'ordering': ['academic_year', 'student'],
            },
        ),
        migrations.CreateModel(
            name='PromotionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staffprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('promotion_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='promotion.promotionrecord')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_mark', models.IntegerField(default=40, help_text='Minimum percentage required to pass')),
                ('rule_type', models.CharField(choices=[('LAST_SET_ONLY', 'Use Last Exam Set Only'), ('SELECTED_SETS', 'Use Selected Exam Sets')], default='LAST_SET_ONLY', max_length=20)),
                ('selected_exam_sets', models.JSONField(blank=True, help_text='List of exam set IDs to use when rule_type is SELECTED_SETS', null=True)),
                ('require_all_compulsory', models.BooleanField(default=True, help_text='Student must pass all compulsory subjects')),
                ('allow_manual_override', models.BooleanField(default=True, help_text='Allow manual promotion decision override')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='schools.academicyear')),
                ('class_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='academic.class')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='core.school')),
            ],
            options={
                'ordering': ['academic_year', 'class_obj'],
                'unique_together': {('school', 'class_obj', 'academic_year')},
            },
        ),
    ]
