# Generated by Django 6.0.1 on 2026-01-18 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(max_length=10, unique=True)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('currency', models.CharField(default='UGX', max_length=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_mark_default', models.IntegerField(default=40)),
                ('promotion_rule_type', models.CharField(choices=[('LAST_SET_ONLY', 'Use Last Exam Set Only'), ('SELECTED_SETS', 'Use Selected Exam Sets')], default='LAST_SET_ONLY', max_length=20)),
                ('require_all_compulsory_for_promotion', models.BooleanField(default=True)),
                ('allow_manual_promotion_override', models.BooleanField(default=True)),
                ('auto_approve_results', models.BooleanField(default=False)),
                ('invoice_group_by_parent', models.BooleanField(default=True)),
                ('allow_overpayment', models.BooleanField(default=True)),
                ('require_refund_approval', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='core.school')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('sync', 'Sync'), ('login', 'Login'), ('logout', 'Logout')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_offline', models.BooleanField(default=False)),
                ('sync_batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.school')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='core_auditl_model_n_3fb686_idx'), models.Index(fields=['school', 'timestamp'], name='core_auditl_school__3d6e5f_idx'), models.Index(fields=['user', 'timestamp'], name='core_auditl_user_id_7b678c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SequenceNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('sequence', models.IntegerField(default=0)),
                ('model_name', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.school')),
            ],
            options={
                'unique_together': {('school', 'prefix', 'year', 'model_name')},
            },
        ),
    ]
