# Generated by Django 6.0.1 on 2026-01-18 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='open', max_length=20)),
                ('device_id', models.CharField(blank=True, max_length=100)),
                ('total_items', models.IntegerField(default=0)),
                ('processed_items', models.IntegerField(default=0)),
                ('failed_items', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_batches', to='core.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create_student', 'Create Student'), ('update_student', 'Update Student'), ('create_result', 'Create Result'), ('update_result', 'Update Result'), ('create_payment', 'Create Payment'), ('update_payment', 'Update Payment'), ('create_enrollment', 'Create Enrollment'), ('update_enrollment', 'Update Enrollment'), ('custom', 'Custom Action')], max_length=50)),
                ('payload', models.JSONField(help_text='Data payload for the action')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('conflict', 'Conflict')], default='pending', max_length=20)),
                ('priority', models.IntegerField(default=0, help_text='Higher = processed first')),
                ('created_offline_at', models.DateTimeField()),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('batch_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to='core.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_queue', to='staff.staffprofile')),
            ],
            options={
                'ordering': ['-priority', 'created_offline_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('result', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('conflict', 'Conflict')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('response_data', models.JSONField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('sync_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='offline.syncqueue')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ConflictRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conflict_type', models.CharField(max_length=100)),
                ('server_data', models.JSONField(blank=True, null=True)),
                ('client_data', models.JSONField(blank=True, null=True)),
                ('resolution', models.CharField(blank=True, choices=[('server_wins', 'Server Wins'), ('client_wins', 'Client Wins'), ('manual', 'Manual Resolution'), ('merged', 'Merged')], max_length=20, null=True)),
                ('resolved_data', models.JSONField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conflicts_resolved', to='staff.staffprofile')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.school')),
                ('sync_queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='offline.syncqueue')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['status', 'priority'], name='offline_syn_status_1c8970_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['staff', 'status'], name='offline_syn_staff_i_40ae53_idx'),
        ),
        migrations.AddIndex(
            model_name='syncqueue',
            index=models.Index(fields=['batch_id'], name='offline_syn_batch_i_a12ba3_idx'),
        ),
    ]
